In [2]:
import pyarrow
# 或者
import fastparquet

In [1]:
import pandas as pd
trainSerise1 = pd.read_parquet("./check_data/part-0.parquet")
trainSerise1

,step,X,Y,Z,enmo,anglez,non-wear_flag,light,battery_voltage,time_of_day,weekday,quarter,relative_date_PCIAT
0,0,0.007187,0.010240,-1.003249,0.004053,-89.308716,0.0,151.600006,4157.000000,44980000000000,4,4,-4.0
1,1,0.006702,0.010651,-1.001471,0.001849,-89.262321,0.0,42.000000,4156.666504,44985000000000,4,4,-4.0
2,2,0.007026,0.010484,-0.999771,0.000706,-89.276512,0.0,6.250000,4156.333496,44990000000000,4,4,-4.0
3,3,0.007181,0.010638,-0.998386,0.000320,-89.248199,0.0,133.600006,4156.000000,44995000000000,4,4,-4.0
4,4,0.007116,0.010715,-0.997445,0.000134,-89.272224,0.0,79.500000,4155.666504,45000000000000,4,4,-4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
97043,97043,0.270359,0.641648,-0.694602,0.000000,-44.923588,0.0,5.000000,3095.000000,18935000000000,3,4,2.0
97044,97044,0.270514,0.640723,-0.695922,0.000000,-45.030350,0.0,5.000000,3095.000000,18940000000000,3,4,2.0
97045,97045,0.271123,0.640711,-0.695321,0.000000,-44.969856,0.0,5.000000,3095.000000,18945000000000,3,4,2.0
97046,97046,0.270527,0.641173,-0.694994,0.000000,-44.952236,0.0,5.000000,3095.000000,18950000000000,3,4,2.0
97047,97047,0.271847,0.639722,-0.695844,0.000000,-45.009029,0.0,5.000000,3095.000000,18955000000000,3,4,2.0

In [3]:
trainSerise1.drop("step", axis=1, inplace=True)
trainSerise1

,X,Y,Z,enmo,anglez,non-wear_flag,light,battery_voltage,time_of_day,weekday,quarter,relative_date_PCIAT
0,0.007187,0.010240,-1.003249,0.004053,-89.308716,0.0,151.600006,4157.000000,44980000000000,4,4,-4.0
1,0.006702,0.010651,-1.001471,0.001849,-89.262321,0.0,42.000000,4156.666504,44985000000000,4,4,-4.0
2,0.007026,0.010484,-0.999771,0.000706,-89.276512,0.0,6.250000,4156.333496,44990000000000,4,4,-4.0
3,0.007181,0.010638,-0.998386,0.000320,-89.248199,0.0,133.600006,4156.000000,44995000000000,4,4,-4.0
4,0.007116,0.010715,-0.997445,0.000134,-89.272224,0.0,79.500000,4155.666504,45000000000000,4,4,-4.0
...,...,...,...,...,...,...,...,...,...,...,...,...
97043,0.270359,0.641648,-0.694602,0.000000,-44.923588,0.0,5.000000,3095.000000,18935000000000,3,4,2.0
97044,0.270514,0.640723,-0.695922,0.000000,-45.030350,0.0,5.000000,3095.000000,18940000000000,3,4,2.0
97045,0.271123,0.640711,-0.695321,0.000000,-44.969856,0.0,5.000000,3095.000000,18945000000000,3,4,2.0
97046,0.270527,0.641173,-0.694994,0.000000,-44.952236,0.0,5.000000,3095.000000,18950000000000,3,4,2.0
97047,0.271847,0.639722,-0.695844,0.000000,-45.009029,0.0,5.000000,3095.000000,18955000000000,3,4,2.0

In [4]:
sensorFeature =trainSerise1.columns.to_list()
sensorFeature , len(sensorFeature)

(['X',
  'Y',
  'Z',
  'enmo',
  'anglez',
  'non-wear_flag',
  'light',
  'battery_voltage',
  'time_of_day',
  'weekday',
  'quarter',
  'relative_date_PCIAT'],
 12)

In [7]:
trainSerise1.describe()

,X,Y,Z,enmo,anglez,non-wear_flag,light,battery_voltage,time_of_day,weekday,quarter,relative_date_PCIAT
count,97048.000000,97048.000000,97048.000000,97048.000000,97048.000000,97048.0,97048.000000,97048.000000,9.704800e+04,97048.000000,97048.0,97048.000000
mean,0.018670,0.071660,-0.061682,0.058280,-5.059758,0.0,54.893394,3974.910645,4.343573e+13,4.168412,4.0,-1.168288
std,0.595251,0.508311,0.578022,0.197285,39.994808,0.0,230.972397,119.525154,2.541039e+13,2.181610,0.0,1.677293
min,-2.143912,-3.373025,-1.003249,0.000000,-89.308716,0.0,0.000000,3095.000000,0.000000e+00,1.000000,4.0,-4.000000
25%,-0.514300,-0.254007,-0.562416,0.001604,-35.037018,0.0,2.367827,3940.479187,2.046875e+13,2.000000,4.0,-3.000000
50%,0.036376,0.096187,-0.042274,0.010466,-2.822715,0.0,7.059160,3994.000000,4.473000e+13,5.000000,4.0,-1.000000
75%,0.539581,0.458349,0.394637,0.038781,22.951601,0.0,19.320485,4046.000000,6.511500e+13,6.000000,4.0,0.000000
max,3.341210,4.442658,2.321265,6.307294,88.389679,0.0,2618.000000,4157.000000,8.639500e+13,7.000000,4.0,2.000000

In [5]:
statFeat = trainSerise1.describe().index.to_list() 
statFeat, len(statFeat)

(['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'], 8)

In [8]:
# generate senor feature statistic column list
sensorStatCol = []
for sta in statFeat: # start statist row 
    # print(sta)
    for item in sensorFeature:
        # print(item)
        sensorStatCol.append(f"{item}_{sta}")
        
sensorStatCol, len(sensorStatCol)

(['X_count',
  'Y_count',
  'Z_count',
  'enmo_count',
  'anglez_count',
  'non-wear_flag_count',
  'light_count',
  'battery_voltage_count',
  'time_of_day_count',
  'weekday_count',
  'quarter_count',
  'relative_date_PCIAT_count',
  'X_mean',
  'Y_mean',
  'Z_mean',
  'enmo_mean',
  'anglez_mean',
  'non-wear_flag_mean',
  'light_mean',
  'battery_voltage_mean',
  'time_of_day_mean',
  'weekday_mean',
  'quarter_mean',
  'relative_date_PCIAT_mean',
  'X_std',
  'Y_std',
  'Z_std',
  'enmo_std',
  'anglez_std',
  'non-wear_flag_std',
  'light_std',
  'battery_voltage_std',
  'time_of_day_std',
  'weekday_std',
  'quarter_std',
  'relative_date_PCIAT_std',
  'X_min',
  'Y_min',
  'Z_min',
  'enmo_min',
  'anglez_min',
  'non-wear_flag_min',
  'light_min',
  'battery_voltage_min',
  'time_of_day_min',
  'weekday_min',
  'quarter_min',
  'relative_date_PCIAT_min',
  'X_25%',
  'Y_25%',
  'Z_25%',
  'enmo_25%',
  'anglez_25%',
  'non-wear_flag_25%',
  'light_25%',
  'battery_voltage_25%',
  'time_of_day_25%',
  'weekday_25%',
  'quarter_25%',
  'relative_date_PCIAT_25%',
  'X_50%',
  'Y_50%',
  'Z_50%',
  'enmo_50%',
  'anglez_50%',
  'non-wear_flag_50%',
  'light_50%',
  'battery_voltage_50%',
  'time_of_day_50%',
  'weekday_50%',
  'quarter_50%',
  'relative_date_PCIAT_50%',
  'X_75%',
  'Y_75%',
  'Z_75%',
  'enmo_75%',
  'anglez_75%',
  'non-wear_flag_75%',
  'light_75%',
  'battery_voltage_75%',
  'time_of_day_75%',
  'weekday_75%',
  'quarter_75%',
  'relative_date_PCIAT_75%',
  'X_max',
  'Y_max',
  'Z_max',
  'enmo_max',
  'anglez_max',
  'non-wear_flag_max',
  'light_max',
  'battery_voltage_max',
  'time_of_day_max',
  'weekday_max',
  'quarter_max',
  'relative_date_PCIAT_max'],
 96)